### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by Epistol** [spatie/docs.spatie.be#1]
```
403 Forbidden
nginx/1.9.11
```

:/ 

and on already set url : 

```
502 Bad Gateway
nginx/1.9.11
```

plus something that look like a certificate error.

**Comment by riasvdv** [comment]
We're aware of the certificate error, we acted a bit too soon in deleting the old site without waiting for DNS to propagate everywhere.

Please sit tight, it'll be back online soon!
