### ISSUE TITLE
PR for css fix

### ISSUE THREAD

**Issue by sinnbeck** [spatie/docs.spatie.be#11]
I have noticed a small issue with the headers in the docs, and figured I would make a PR for a fix. It seems that the resources directory is not version controlled, which means it isnt possible.

The issue is headers that have code in them like this: https://spatie.be/docs/laravel-query-builder/v3/introduction#filter-a-query-based-on-a-request-usersfilternamejohn
It seems that people are copy pasting that example from the header into their code and are confused by it not working. The cause is that it is all uppercase, which is caused by the css on the element.

My suggestion was to add this to the css
```
.markup-titles h3 code, .markup-titles h4 code {
        text-transform: initial;
}

**Comment by willemvb** [comment]
Hey René, thanks for the suggestion!

I've fixed it in the spatie.be repo: https://github.com/spatie/spatie.be/blob/master/resources/css/front/utilities/markup.css#L94-L96
(Docs now live under https://spatie.be/docs)
