### ISSUE TITLE
[Idea] show CarbonADS

### ISSUE THREAD

**Issue by Gummibeer** [spatie/docs.spatie.be#6]
I've seen CarbonAds a lot on documentation pages already. So I had the idea to add them to spatie docs for some extra income?
I've no idea how much this could be and if it's worth and if you want this at all? But I wanted to share it with you and let you decide. If not it's 100% fine for me.
https://www.carbonads.net

**Comment by freekmurze** [comment]
We've discussed this internally previously and don't want to do this now. Thanks for the suggestion.
