### ISSUE TITLE
Invalid Edit button URL in some scenarios

### ISSUE THREAD

**Issue by adriandmitroca** [spatie/docs.spatie.be#9]
Hi folks,

I have found out that in some cases "Edit on" button is invalid, for example for this library: https://docs.spatie.be/laravel-dashboard/v1/introduction/

I have spent some time trying to fix this, but unfortunately couldn't come up with a solution (touched Go lang & Hugo for the first time in my life).

What I can tell you though, is that bug is caused by this line:
https://github.com/spatie/docs.spatie.be/blob/master/layouts/_default/baseof.html#L4

In this scenario, `.Title` is equal to `v8` which causes the bug in the first place. Might be something related to variable reference (only place that `v8` variable exists is spatie/media-library repo).

Hope that helps.

**Comment by riasvdv** [comment]
Seems like it was just a wrong version in https://github.com/spatie/laravel-dashboard/blob/master/docs/_index.md
